import { Metadata } from "next";
import { Inter } from 'next/font/google';
import Link from "next/link";
const inter =  Inter({ subsets: ['latin'] })
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children, }: { children: React.ReactNode } ){
  return (
      <html lang="en">
            <body className={inter.className}>
                <header className="bg-blue-600 text-white p-4 flex justify-between">
                    <h1 className="font-bold">NextJS CRUD Demo</h1>
                    <nav className="space-x-4">
                        <Link href="/categories">Categories</Link>
                        <Link href="/products">Products</Link>
                    </nav>
                </header>
                <main className="p-6">{children}</main>
            </body>
        </html>
  );
}
